[pytest]
pythonpath = . src
# Tell pytest-django where the fake settings file is located
DJANGO_SETTINGS_MODULE = tests.settings

# Tell pytest what files to look for
python_files = tests.py test_*.py *_tests.py

# Optional: Make output easier to read
addopts = -v --reuse-db