# Generated by Django 6.0 on 2025-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemerrorlog',
            name='reported_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
