# Generated by Django 6.0 on 2025-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0002_alter_systemerrorlog_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemerrorlog',
            name='method_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
