# Generated by Django 6.0 on 2025-12-25 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0004_abstractbanneduser_is_deactivated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractGuestIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivated_by', models.CharField(blank=True, max_length=250, null=True)),
                ('session_key', models.CharField(db_index=True, help_text="The UUID stored in the user's cookie.", max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_history', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractSessionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_deactivated', models.BooleanField(default=False)),
                ('deactivated_by', models.CharField(blank=True, max_length=250, null=True)),
                ('curent_session_key', models.CharField(db_index=True, max_length=255)),
                ('previous_session_key', models.CharField(db_index=True, max_length=255)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('session_count', models.IntegerField(default=1)),
                ('shared_device_hash', models.CharField(blank=True, max_length=255)),
                ('abstract_guest_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user_links', to='django_abstract.abstractguestidentity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='abstractguestidentity',
            index=models.Index(fields=['session_key'], name='django_abst_session_ad1fb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='abstractsessionlink',
            unique_together={('user', 'abstract_guest_user')},
        ),
    ]
