# Generated by Django 6.0 on 2025-12-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0005_abstractguestidentity_abstractsessionlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsessionmetrics',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
