# Generated by Django 6.0.4 on 2026-04-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0006_alter_abstractsessionmetrics_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractauthenticatedmoderegestry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractauthenticatedmoderegestry',
            name='guest_mode_regestry',
        ),
        migrations.RemoveField(
            model_name='abstractauthenticatedmoderegestry',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='abstractauthenticatedmoderegestry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='abstractbanneduser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractbanneduser',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='abstractguestidentity',
            name='django_abst_session_ad1fb4_idx',
        ),
        # migrations.RemoveField(
        #     model_name='abstractsessionlink',
        #     name='abstract_guest_user',
        # ),
        migrations.RemoveField(
            model_name='abstractguestmoderegestry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractguestmoderegestry',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='abstractsessionlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='abstractsessionlink',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractsessionlink',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='abstractsessionlink',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='abstractsessionmetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='abstractsessionmetrics',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractsessionmetrics',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AbstractAuthenticatedModeRegestry',
        ),
        migrations.DeleteModel(
            name='AbstractBannedUser',
        ),
        migrations.RemoveField(
            model_name='abstractguestidentity',
            name='converted_user',
        ),
        migrations.RemoveField(
            model_name='abstractguestidentity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='abstractguestidentity',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AbstractGuestModeRegestry',
        ),
        migrations.DeleteModel(
            name='AbstractSessionLink',
        ),
        migrations.DeleteModel(
            name='AbstractSessionMetrics',
        ),
        migrations.DeleteModel(
            name='AbstractGuestIdentity',
        ),
    ]
