# Generated by Django 6.0.4 on 2026-05-23 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_abstract', '0007_remove_abstractauthenticatedmoderegestry_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='featuretoggle',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genericactivitylog',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemerrorlog',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
